image:
  repository: "ghcr.io/homarr-labs/homarr"
  tag: "v1.43.3@sha256:e3112f8d2e9aa32d0d3e69950ac76111f725714b68bca488a01c0afa6811a238"
  pullPolicy: "IfNotPresent"
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            NEXTAUTH_SECRET:
              secretKeyRef:
                name: homarr-secrets
                key: NEXTAUTH_SECRET
service:
  main:
    ports:
      main:
        port: 10245
        targetPort: 7575
persistence:
  config:
    enabled: true
    mountPath: "/app/data/configs"
  icons:
    enabled: true
    mountPath: "/app/public/icons"
  data:
    enabled: true
    mountPath: "/data"
portal:
  open:
    enabled: true
