image:
  repository: "ghcr.io/homarr-labs/homarr"
  tag: "v1.44.0@sha256:1fe93befc07274f6fb64d7772cec24d1f3be1e344274112a69e992d495521fd2"
  pullPolicy: "IfNotPresent"
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            NEXTAUTH_SECRET:
              secretKeyRef:
                name: homarr-secrets
                key: NEXTAUTH_SECRET
service:
  main:
    ports:
      main:
        port: 10245
        targetPort: 7575
persistence:
  config:
    enabled: true
    mountPath: "/app/data/configs"
  icons:
    enabled: true
    mountPath: "/app/public/icons"
  data:
    enabled: true
    mountPath: "/data"
portal:
  open:
    enabled: true
