image:
  repository: "ghcr.io/pi-hole/pihole"
  pullPolicy: "IfNotPresent"
  tag: "2025.11.1@sha256:91dc91ddd413bf461c283204558f8f21839851e9824799075a7ceff7c77eea40"
pihole:
  webPassword: somepassword"
  dnsServers:
  - "9.9.9.9"
  - "149.112.112.112"
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    allowPrivilegeEscalation: true
    runAsUser: 0
    runAsGroup: 0
    capabilities:
      add:
      - NET_ADMIN
      - SETFCAP
      - SETPCAP
      - KILL
workload:
  main:
    podSpec:
      containers:
        main:
          envFrom:
          - configMapRef:
              name: pihole-env
          probes:
            liveness:
              type: http
              path: /admin/index.php
            readiness:
              type: http
              path: /admin/index.php
            startup:
              type: http
              path: /admin/index.php
service:
  main:
    ports:
      main:
        port: 9089
        targetPort: 80
  dns:
    enabled: true
    ports:
      dns:
        enabled: true
        protocol: udp
        port: 53
        targetPort: 53
      dns-tcp:
        enabled: true
        protocol: tcp
        port: "{{ .Values.service.dns.ports.dns.port }}"
        targetPort: 53
persistence:
  config:
    enabled: true
    mountPath: "/etc/pihole"
  dnsmasq:
    enabled: true
    mountPath: "/etc/dnsmasq.d"
portal:
  open:
    enabled: true
