image:
  repository: "ghcr.io/rommapp/romm"
  pullPolicy: "IfNotPresent"
  tag: "3.6@sha256:d4ca71e95e1100c84edd07b8a1e6891c4c4eb2e1d74b5dc73e4d7b64c3b44a12"

securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0

service:
  main:
    ports:
      main:
        protocol: http
        targetPort: 8080
        port: 10680

romm:
  auth:
    user: "admin"
    pass: "admin"

workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              type: http
            readiness:
              type: http
            startup:
              type: http
          env:
            ROMM_BASE_PATH: /romm
            ROMM_DB_DRIVER: mariadb
            # IGDB client id
            CLIENT_ID: ""
            # IGDB client secret
            CLIENT_SECRET: ""
            STEAMGRIDDB_API_KEY: ""
            DB_PORT: 3306
            DB_NAME: "{{ .Values.mariadb.mariadbDatabase }}"
            DB_USER: "{{ .Values.mariadb.mariadbUsername }}"
            DB_HOST:
              secretKeyRef:
                expandObjectName: false
                name: '{{ printf "%s-%s" .Release.Name "mariadbcreds" }}'
                key: plainhost
            DB_PASSWD: "{{ .Values.mariadb.password }}"
            REDIS_HOST:
              secretKeyRef:
                expandObjectName: false
                name: '{{ printf "%s-%s" .Release.Name "rediscreds" }}'
                key: plainhost
            REDIS_PASSWORD: "{{ .Values.redis.password }}"
            REDIS_PORT: 6379
            ROMM_AUTH_SECRET_KEY:
              secretKeyRef:
                name: romm-secrets
                key: ROMM_AUTH_SECRET_KEY
            ROMM_AUTH_ENABLED: true
            ENABLE_EXPERIMENTAL_REDIS: true
            ROMM_AUTH_USERNAME: "{{ .Values.romm.auth.user}}"
            ROMM_AUTH_PASSWORD: "{{ .Values.romm.auth.pass}}"

persistence:
  library:
    enabled: true
    mountPath: /romm/library
  resources:
    enabled: true
    mountPath: /romm/resources
  config:
    enabled: true
    mountPath: /romm/config
  assets:
    enabled: true
    mountPath: /romm/assets

mariadb:
  enabled: true
  includeCommon: true
  mariadbUsername: romm
  mariadbDatabase: romm

redis:
  enabled: true
  includeCommon: true

portal:
  open:
    enabled: true
