image:
  repository: "docker.io/seafileltd/seafile-mc"
  tag: "12.0.11@sha256:4ab87f4b7fd9a712f614386c3362049d1701161e07e0f88681fdddcc3e543680"
  pullPolicy: "IfNotPresent"
service:
  main:
    ports:
      main:
        port: 13080
        protocol: http
        targetPort: 80
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            DB_HOST:
              secretKeyRef:
                expandObjectName: false
                name: '{{ printf "%s-%s" .Release.Name "mariadbcreds" }}'
                key: plainhost
            DB_ROOT_PASSWD: "{{ .Values.mariadb.rootPassword }}"
            SEAFILE_SERVER_LETSENCRYPT: false
            SEAFILE_SERVER_HOSTNAME: ""
            SEAFILE_ADMIN_EMAIL: me@example.com
            SEAFILE_ADMIN_PASSWORD: a_very_secret_password
            FORCE_HTTPS_IN_CONF: false
persistence:
  storage:
    enabled: true
    mountPath: "/shared/seafile"
mariadb:
  enabled: true
  includeCommon: true
  mariadbUsername: seafile
  mariadbDatabase: seafile
portal:
  open:
    enabled: true
