image:
  pullPolicy: IfNotPresent
  repository: docker.io/cloudreve/cloudreve
  tag: 4.8.0@sha256:a553e5138ffc039388a0b45124189d0dec08f0c9b90d57469dc6240df9bfa452
persistence:
  avatarpath:
    enabled: true
    mountPath: /cloudreve/avatar
  config:
    enabled: true
    targetSelector:
      main:
        main:
          mountPath: /cloudreve
        init:
          mountPath: /conf-init
  uploadpath:
    enabled: true
    mountPath: /cloudreve/uploads
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsGroup: 0
    runAsUser: 0
workload:
  main:
    podSpec:
      initContainers:
        init:
          enabled: true
          type: init
          imageSelector: image
          command:
          - "/bin/sh"
          - "-c"
          - |
            set -x
            ls -lasth /cloudreve
            cp -a /cloudreve/cloudreve /conf-init/cloudreve
            ls -lasht /conf-init
      containers:
        main: {}
service:
  main:
    ports:
      main:
        port: 5212
        targetPort: 5212
portal:
  open:
    enabled: true
