hastyPaste:
  branding:
    css_file: ""
    description: ""
    favicon: ""
    hide_version: false
    icon: ""
    title: ""
  enable_public_list: false
  interface:
    default_expire_time_days: 0
    default_expire_time_enable: false
    default_expire_time_hours: 1
    default_expire_time_minutes: 0
    default_use_long_id: false
  log_level: INFO
  max_body_size: 2000000
  new_at_index: false
  workers: 1
image:
  pullPolicy: IfNotPresent
  repository: ghcr.io/enchant97/hasty-paste
  tag: 2.3.0@sha256:b6d7f307fd45e66138812bae1503a383367dfce69b0629cc25a5f285fb141287
persistence:
  config:
    enabled: true
    mountPath: /app/data
portal:
  open:
    enabled: true
redis:
  enabled: true
  username: default
service:
  main:
    ports:
      main:
        port: 10601
        protocol: http
workload:
  main:
    podSpec:
      containers:
        main:
          envFrom:
          - secretRef:
              name: hastypaste-secrets
          probes:
            liveness:
              custom: true
              enabled: true
              spec:
                exec:
                  command:
                  - /bin/sh
                  - health-check.sh
            readiness:
              custom: true
              enabled: true
              spec:
                exec:
                  command:
                  - /bin/sh
                  - health-check.sh
            startup:
              custom: true
              enabled: true
              spec:
                exec:
                  command:
                  - /bin/sh
                  - health-check.sh
