image:
  repository: "ghcr.io/homarr-labs/homarr"
  tag: "v1.43.1@sha256:a370e506348d3f796da3ef5c3519fc2183541c20ca4f082f0804c696f289a048"
  pullPolicy: "IfNotPresent"
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            NEXTAUTH_SECRET:
              secretKeyRef:
                name: homarr-secrets
                key: NEXTAUTH_SECRET
service:
  main:
    ports:
      main:
        port: 10245
        targetPort: 7575
persistence:
  config:
    enabled: true
    mountPath: "/app/data/configs"
  icons:
    enabled: true
    mountPath: "/app/public/icons"
  data:
    enabled: true
    mountPath: "/data"
portal:
  open:
    enabled: true
